package gnipa_studio

// The emitters: each produces the complete text of one src/gen_*.odin file
// from the COMPILED game tables (import game "../../src") plus the notes.txt
// comment sidecar.  There is no Odin parser anywhere — reading is the import,
// writing is these procs, and --emit-check pins that the two agree.
//
// The emitter is also the formatter: gen files have no other style authority.

import "core:fmt"
import "core:strings"
import rl "vendor:raylib"
import game "../../src"

GEN_HEADER :: `// GENERATED by tools/gnipa_studio — do not hand-edit.
// Edit through the studio (or re-run gnipa_studio --extract) and this file is
// rewritten wholesale; row comments live in tools/gnipa_studio/notes.txt.
// Verify with: gnipa_studio --emit-check
`

// ─── Small pieces ─────────────────────────────────────────────────────────────

escape_odin_string :: proc(s: string, allocator := context.allocator) -> string {
	if !strings.contains_any(s, "\\\"") do return s
	b: strings.Builder
	strings.builder_init(&b, allocator)
	for i in 0 ..< len(s) {
		c := s[i]
		if c == '\\' || c == '"' do strings.write_byte(&b, '\\')
		strings.write_byte(&b, c)
	}
	return strings.to_string(b)
}

color_str :: proc(c: rl.Color) -> string {
	if c == {} do return "{}"
	return fmt.tprintf("{{%d, %d, %d, %d}}", c.r, c.g, c.b, c.a)
}

pal_str :: proc(pal: game.Icon_Palette) -> string {
	if pal == {} do return "{}"
	if name := pal_name_for(pal); name != "" do return name
	return fmt.tprintf("{{%s, %s, %s, %s, %s}}",
		color_str(pal.base), color_str(pal.dark), color_str(pal.light),
		color_str(pal.accent), color_str(pal.accent2))
}

ingredient_str :: proc(ing: game.Ingredient) -> string {
	if ing.item == .None do return "{}"
	return fmt.tprintf("{{.%v, %d}}", ing.item, ing.count)
}

write_grid_body :: proc(b: ^strings.Builder, grid: game.Icon_Grid, indent: string) {
	fmt.sbprintf(b, "Icon_Grid{{\n")
	for row in grid {
		fmt.sbprintf(b, "%s\t\"%s\",\n", indent, escape_odin_string(row, context.temp_allocator))
	}
	fmt.sbprintf(b, "%s}}", indent)
}

// ─── gen_items.odin ───────────────────────────────────────────────────────────

emit_items :: proc(notes: ^Notes, allocator := context.allocator) -> string {
	b: strings.Builder
	strings.builder_init(&b, allocator)

	fmt.sbprintf(&b, "package game\n\n%s\n", GEN_HEADER)

	fmt.sbprintf(&b, "// One display/behavior row per item (Item_Info in items.odin).\n")
	fmt.sbprintf(&b, "@(rodata)\nitem_table := [Item]Item_Info{{\n")
	for info, it in game.item_table {
		notes_write(&b, notes, "item", fmt.tprintf("%v", it), "\t")
		fmt.sbprintf(&b, "\t.%v = {{ \"%s\", %s, .%v, \"%s\" }},\n",
			it,
			escape_odin_string(info.name, context.temp_allocator),
			color_str(info.color),
			info.place_tile,
			escape_odin_string(info.desc, context.temp_allocator))
	}
	fmt.sbprintf(&b, "}}\n\n")

	fmt.sbprintf(&b, "// Which equip slot an item occupies; absent (= .None) is not equippable.\n")
	fmt.sbprintf(&b, "// Stat bonuses stay hand-owned in items.odin (they reference named constants).\n")
	fmt.sbprintf(&b, "@(rodata)\nitem_equip_slot := #partial [Item]Equip_Slot{{\n")
	for slot, it in game.item_equip_slot {
		if slot == .None do continue
		notes_write(&b, notes, "equip", fmt.tprintf("%v", it), "\t")
		fmt.sbprintf(&b, "\t.%v = .%v,\n", it, slot)
	}
	fmt.sbprintf(&b, "}}\n")

	return strings.to_string(b)
}

// ─── gen_item_icons.odin ──────────────────────────────────────────────────────

emit_icons :: proc(notes: ^Notes, allocator := context.allocator) -> string {
	b: strings.Builder
	strings.builder_init(&b, allocator)

	fmt.sbprintf(&b, "package game\n\n%s\n", GEN_HEADER)
	fmt.sbprintf(&b, "// Shared 12x12 shape grids and tier palettes, then one Item_Icon per item.\n")
	fmt.sbprintf(&b, "// Legend and drawing live in item_art.odin (icon_pixel / draw_item_icon);\n")
	fmt.sbprintf(&b, "// which names exist here is mirrored by tools/gnipa_studio/registry.odin.\n\n")

	fmt.sbprintf(&b, "// Metal tiers, echoing the old flat item_table colors so gear stays readable.\n")
	for e in pal_registry {
		fmt.sbprintf(&b, "%s :: Icon_Palette{{%s, %s, %s, %s, %s}}\n",
			e.name,
			color_str(e.pal.base), color_str(e.pal.dark), color_str(e.pal.light),
			color_str(e.pal.accent), color_str(e.pal.accent2))
	}
	fmt.sbprintf(&b, "\n")

	for e in shape_registry {
		notes_write(&b, notes, "grid", e.name, "")
		fmt.sbprintf(&b, "%s :: ", e.name)
		write_grid_body(&b, e.grid, "")
		fmt.sbprintf(&b, "\n\n")
	}

	fmt.sbprintf(&b, "@(rodata)\nitem_icons := [Item]Item_Icon{{\n")
	for icon, it in game.item_icons {
		notes_write(&b, notes, "icon", fmt.tprintf("%v", it), "\t")
		if icon == {} {
			fmt.sbprintf(&b, "\t.%v = {{}},\n", it)
			continue
		}
		fmt.sbprintf(&b, "\t.%v = {{", it)
		if name := shape_name_for(icon.grid); name != "" {
			fmt.sbprintf(&b, "%s", name)
		} else {
			write_grid_body(&b, icon.grid, "\t")
		}
		fmt.sbprintf(&b, ", %s}},\n", pal_str(icon.pal))
	}
	fmt.sbprintf(&b, "}}\n")

	return strings.to_string(b)
}

// ─── gen_recipes.odin ─────────────────────────────────────────────────────────

emit_recipes :: proc(notes: ^Notes, allocator := context.allocator) -> string {
	b: strings.Builder
	strings.builder_init(&b, allocator)

	fmt.sbprintf(&b, "package game\n\n%s\n", GEN_HEADER)

	fmt.sbprintf(&b, "// The crafting table.  APPEND-ONLY: recipe indices are load-bearing for\n")
	fmt.sbprintf(&b, "// tests — never insert, delete or reorder rows.  Types and craft logic live\n")
	fmt.sbprintf(&b, "// in crafting.odin.\n")
	fmt.sbprintf(&b, "@(rodata)\nrecipe_table := [?]Recipe{{\n")
	for r in game.recipe_table {
		notes_write(&b, notes, "recipe", fmt.tprintf("%v", r.result), "\t")
		fmt.sbprintf(&b, "\t{{ .%v, %d, .%v, {{%s, %s, %s}} }},\n",
			r.result, r.result_count, r.station,
			ingredient_str(r.ingredients[0]),
			ingredient_str(r.ingredients[1]),
			ingredient_str(r.ingredients[2]))
	}
	fmt.sbprintf(&b, "}}\n\n")

	fmt.sbprintf(&b, "// Recipe unlock tree: a recipe stays hidden until the player first holds its\n")
	fmt.sbprintf(&b, "// gating material — keyed by the recipe's (unique) RESULT item; absent\n")
	fmt.sbprintf(&b, "// (= .None) means known from the start.  The unlock is STICKY\n")
	fmt.sbprintf(&b, "// (Progression_State.recipe_unlocked): once held, available forever.\n")
	fmt.sbprintf(&b, "// Tuning the pace of the early game = editing this table.\n")
	fmt.sbprintf(&b, "@(rodata)\nrecipe_unlock := #partial [Item]Item{{\n")
	emitted: [game.Item]bool
	for r in game.recipe_table {
		if emitted[r.result] do continue
		emitted[r.result] = true
		gate := game.recipe_unlock[r.result]
		if gate == .None do continue
		notes_write(&b, notes, "unlock", fmt.tprintf("%v", r.result), "\t")
		fmt.sbprintf(&b, "\t.%v = .%v,\n", r.result, gate)
	}
	for gate, it in game.recipe_unlock {
		// Defensive: gates on items that are not recipe results still emit.
		if gate == .None || emitted[it] do continue
		notes_write(&b, notes, "unlock", fmt.tprintf("%v", it), "\t")
		fmt.sbprintf(&b, "\t.%v = .%v,\n", it, gate)
	}
	fmt.sbprintf(&b, "}}\n\n")

	fmt.sbprintf(&b, "// What a smelter eats and what it casts.  New smeltable = new row.\n")
	fmt.sbprintf(&b, "// Smelt_Rule and the smelter logic live in sim.odin.\n")
	fmt.sbprintf(&b, "@(rodata)\nsmelt_table := [?]Smelt_Rule{{\n")
	for r in game.smelt_table {
		notes_write(&b, notes, "smelt", fmt.tprintf("%v", r.ore), "\t")
		fmt.sbprintf(&b, "\t{{ .%v, .%v, %d }},\n", r.ore, r.bar, r.ore_per_bar)
	}
	fmt.sbprintf(&b, "}}\n")

	return strings.to_string(b)
}
