package gnipa_studio

// The emitters: each produces the complete text of one src/gen_*.odin file.
// There is no Odin parser anywhere — reading is `import game "../../src"`,
// writing is these procs, and --emit-check pins that the two agree.
//
// Icons emit from an editable VIEW (cells + palette per item, named working
// shapes), so the pixel editor saves the same way --extract does: the views
// are seeded from the compiled tables and the editor mutates them in place.
//
// The emitter is also the formatter: gen files have no other style authority.

import "core:fmt"
import "core:os"
import "core:strings"
import rl "vendor:raylib"
import game "../../src"

GEN_HEADER :: `// GENERATED by tools/gnipa_studio — do not hand-edit.
// Edit through the studio (or re-run gnipa_studio --extract) and this file is
// rewritten wholesale; row comments live in tools/gnipa_studio/notes.txt.
// Verify with: gnipa_studio --emit-check
`

// ─── Icon views: the editable representation ──────────────────────────────────

Icon_Cells :: [game.ICON_GRID][game.ICON_GRID]u8

Icon_View :: struct {
	cells: Icon_Cells,
	pal:   game.Icon_Palette,
	empty: bool, // .None: emits {}
}

Shape_View :: struct {
	name:  string,
	cells: Icon_Cells,
}

cells_from_grid :: proc(grid: game.Icon_Grid) -> (c: Icon_Cells) {
	for &row in c do for &ch in row do ch = '.'
	for row, y in grid {
		for x in 0 ..< min(len(row), game.ICON_GRID) do c[y][x] = row[x]
	}
	return
}

views_from_game :: proc(views: ^[game.Item]Icon_View) {
	for icon, it in game.item_icons {
		if icon == {} {
			views[it] = {empty = true}
			continue
		}
		views[it] = {cells = cells_from_grid(icon.grid), pal = icon.pal}
	}
}

shapes_from_registry :: proc(shapes: []Shape_View) {
	for e, i in shape_registry {
		shapes[i] = {e.name, cells_from_grid(e.grid)}
	}
}

// An item is ATTACHED to a registry shape only if its row in the gen file on
// disk references the constant by name — an inline grid, even byte-identical
// to a shape, is an independent copy and stays one across sessions.  Grid
// equality alone no longer attaches (the wizard's copy-art made GreenBerrie a
// live LEAF_GRID reference that way).  The gen file itself is the record; a
// missing file (first --extract) attaches everything so equality decides.
Icon_Anchors :: [game.Item]bool

anchors_from_gen_file :: proc() -> (anchored: Icon_Anchors) {
	data, err := os.read_entire_file_from_path(SRC_DIR + "gen_item_icons.odin", context.allocator)
	if err != nil {
		for &a in anchored do a = true
		return
	}
	defer delete(data)
	for line in strings.split_lines(string(data)) {
		l := strings.trim_prefix(line, "\t")
		if len(l) < 2 || l[0] != '.' do continue
		eq := strings.index(l, " = {")
		if eq < 0 do continue
		rest := l[eq+4:]
		// A capital identifier right after the brace is a shape constant
		// name — except "Icon_Grid{", which opens an inline grid; '}'
		// closes an empty row.
		if strings.has_prefix(rest, "Icon_Grid{") do continue
		if len(rest) == 0 || rest[0] < 'A' || rest[0] > 'Z' do continue
		ident := l[1:eq]
		for it in game.Item {
			if fmt.tprintf("%v", it) == ident {
				anchored[it] = true
				break
			}
		}
	}
	return
}

// A new item mid-creation: it has no game.Item ordinal yet (the enum line is
// written in the same Save), so its rows are keyed by identifier string and
// appended after the enum-keyed rows — append-only makes it the highest
// ordinal, which is exactly where the enum insert puts it.
Pending_Item :: struct {
	ident:        string, // Odin identifier, e.g. "Mana_Crystal"
	info:         game.Item_Info,
	icon:         Icon_View,
	equip:        game.Equip_Slot,
	has_recipe:   bool,
	result_count: int,
	station:      game.Station,
	ings:         [3]game.Ingredient,
	unlock:       game.Item,
}

// ─── Small pieces ─────────────────────────────────────────────────────────────

escape_odin_string :: proc(s: string, allocator := context.allocator) -> string {
	if !strings.contains_any(s, "\\\"") do return s
	b: strings.Builder
	strings.builder_init(&b, allocator)
	for i in 0 ..< len(s) {
		c := s[i]
		if c == '\\' || c == '"' do strings.write_byte(&b, '\\')
		strings.write_byte(&b, c)
	}
	return strings.to_string(b)
}

color_str :: proc(c: rl.Color) -> string {
	if c == {} do return "{}"
	return fmt.tprintf("{{%d, %d, %d, %d}}", c.r, c.g, c.b, c.a)
}

pal_str :: proc(pal: game.Icon_Palette) -> string {
	if pal == {} do return "{}"
	if name := pal_name_for(pal); name != "" do return name
	return fmt.tprintf("{{%s, %s, %s, %s, %s}}",
		color_str(pal.base), color_str(pal.dark), color_str(pal.light),
		color_str(pal.accent), color_str(pal.accent2))
}

ingredient_str :: proc(ing: game.Ingredient) -> string {
	if ing.item == .None do return "{}"
	return fmt.tprintf("{{.%v, %d}}", ing.item, ing.count)
}

// Flags print in Terrain_Flags' declared bit order, so the text is stable.
terrain_flags_str :: proc(fl: game.Terrain_Flags) -> string {
	if fl == {} do return "{}"
	b: strings.Builder
	strings.builder_init(&b, context.temp_allocator)
	strings.write_string(&b, "{")
	first := true
	for f in game.Terrain_Flag {
		if f not_in fl do continue
		if !first do strings.write_string(&b, ", ")
		fmt.sbprintf(&b, ".%v", f)
		first = false
	}
	strings.write_string(&b, "}")
	return strings.to_string(b)
}

// Minimal float: whole values print as integers, no trailing zeros.
f32_str :: proc(v: f32) -> string {
	if v == f32(int(v)) do return fmt.tprintf("%d", int(v))
	return fmt.tprintf("%v", v)
}

write_cells_body :: proc(b: ^strings.Builder, cells: Icon_Cells, indent: string) {
	fmt.sbprintf(b, "Icon_Grid{{\n")
	for row in cells {
		row := row
		fmt.sbprintf(b, "%s\t\"%s\",\n", indent,
			escape_odin_string(string(row[:]), context.temp_allocator))
	}
	fmt.sbprintf(b, "%s}}", indent)
}

// ─── gen_items.odin ───────────────────────────────────────────────────────────

emit_items :: proc(notes: ^Notes, pending: []Pending_Item, allocator := context.allocator) -> string {
	b: strings.Builder
	strings.builder_init(&b, allocator)

	fmt.sbprintf(&b, "package game\n\n%s\n", GEN_HEADER)

	fmt.sbprintf(&b, "// One display/behavior row per item (Item_Info in items.odin).\n")
	fmt.sbprintf(&b, "@(rodata)\nitem_table := [Item]Item_Info{{\n")
	for info, it in game.item_table {
		notes_write(&b, notes, "item", fmt.tprintf("%v", it), "\t")
		fmt.sbprintf(&b, "\t.%v = {{ \"%s\", %s, .%v, \"%s\" }},\n",
			it,
			escape_odin_string(info.name, context.temp_allocator),
			color_str(info.color),
			info.place_tile,
			escape_odin_string(info.desc, context.temp_allocator))
	}
	for p in pending {
		fmt.sbprintf(&b, "\t.%s = {{ \"%s\", %s, .%v, \"%s\" }},\n",
			p.ident,
			escape_odin_string(p.info.name, context.temp_allocator),
			color_str(p.info.color),
			p.info.place_tile,
			escape_odin_string(p.info.desc, context.temp_allocator))
	}
	fmt.sbprintf(&b, "}}\n\n")

	fmt.sbprintf(&b, "// Which equip slot an item occupies; absent (= .None) is not equippable.\n")
	fmt.sbprintf(&b, "// Stat bonuses stay hand-owned in items.odin (they reference named constants).\n")
	fmt.sbprintf(&b, "@(rodata)\nitem_equip_slot := #partial [Item]Equip_Slot{{\n")
	for slot, it in game.item_equip_slot {
		if slot == .None do continue
		notes_write(&b, notes, "equip", fmt.tprintf("%v", it), "\t")
		fmt.sbprintf(&b, "\t.%v = .%v,\n", it, slot)
	}
	for p in pending {
		if p.equip == .None do continue
		fmt.sbprintf(&b, "\t.%s = .%v,\n", p.ident, p.equip)
	}
	fmt.sbprintf(&b, "}}\n")

	return strings.to_string(b)
}

// ─── gen_item_icons.odin ──────────────────────────────────────────────────────

emit_icons :: proc(notes: ^Notes, views: ^[game.Item]Icon_View, anchored: ^Icon_Anchors, shapes: []Shape_View, pending: []Pending_Item, allocator := context.allocator) -> string {
	b: strings.Builder
	strings.builder_init(&b, allocator)

	fmt.sbprintf(&b, "package game\n\n%s\n", GEN_HEADER)
	fmt.sbprintf(&b, "// Shared 12x12 shape grids and tier palettes, then one Item_Icon per item.\n")
	fmt.sbprintf(&b, "// Legend and drawing live in item_art.odin (icon_pixel / draw_item_icon);\n")
	fmt.sbprintf(&b, "// which names exist here is mirrored by tools/gnipa_studio/registry.odin.\n\n")

	fmt.sbprintf(&b, "// Metal tiers, echoing the old flat item_table colors so gear stays readable.\n")
	for e in pal_registry {
		fmt.sbprintf(&b, "%s :: Icon_Palette{{%s, %s, %s, %s, %s}}\n",
			e.name,
			color_str(e.pal.base), color_str(e.pal.dark), color_str(e.pal.light),
			color_str(e.pal.accent), color_str(e.pal.accent2))
	}
	fmt.sbprintf(&b, "\n")

	for sh in shapes {
		notes_write(&b, notes, "grid", sh.name, "")
		fmt.sbprintf(&b, "%s :: ", sh.name)
		write_cells_body(&b, sh.cells, "")
		fmt.sbprintf(&b, "\n\n")
	}

	shape_of :: proc(shapes: []Shape_View, cells: Icon_Cells) -> string {
		for sh in shapes do if sh.cells == cells do return sh.name
		return ""
	}

	fmt.sbprintf(&b, "@(rodata)\nitem_icons := [Item]Item_Icon{{\n")
	for it in game.Item {
		v := &views[it]
		notes_write(&b, notes, "icon", fmt.tprintf("%v", it), "\t")
		if v.empty {
			fmt.sbprintf(&b, "\t.%v = {{}},\n", it)
			continue
		}
		fmt.sbprintf(&b, "\t.%v = {{", it)
		name := anchored[it] ? shape_of(shapes, v.cells) : ""
		if name != "" {
			fmt.sbprintf(&b, "%s", name)
		} else {
			write_cells_body(&b, v.cells, "\t")
		}
		fmt.sbprintf(&b, ", %s}},\n", pal_str(v.pal))
	}
	// Pending items always inline: art picked in the wizard is a COPY, never a
	// reference to the donor's shape constant.
	for p in pending {
		fmt.sbprintf(&b, "\t.%s = {{", p.ident)
		write_cells_body(&b, p.icon.cells, "\t")
		fmt.sbprintf(&b, ", %s}},\n", pal_str(p.icon.pal))
	}
	fmt.sbprintf(&b, "}}\n")

	return strings.to_string(b)
}

// ─── gen_player_art.odin ──────────────────────────────────────────────────────

Player_Frames :: [game.Player_Form][2][game.FRAME_HEIGHT][game.FRAME_WIDTH]rune

emit_player :: proc(notes: ^Notes, frames: ^Player_Frames, allocator := context.allocator) -> string {
	b: strings.Builder
	strings.builder_init(&b, allocator)

	fmt.sbprintf(&b, "package game\n\n%s\n", GEN_HEADER)
	fmt.sbprintf(&b, "// 16x22 ascii sprites, two walk frames each, shading baked into the art\n")
	fmt.sbprintf(&b, "// (light from above, near-black 'x' outline everywhere).  Legend: h/H/L\n")
	fmt.sbprintf(&b, "// clothing shadow/mid/rim and y/Y hair shadow/mid (player-tinted); k/K skin,\n")
	fmt.sbprintf(&b, "// m/M/N steel, f/F fur, b/B leather, w/W bone, s/S stone (shadow/mid, N =\n")
	fmt.sbprintf(&b, "// highlight); v void/black cloth, E eye glow, O/Q orb core/halo, G/g glowing\n")
	fmt.sbprintf(&b, "// core/ember ring, T gold trim.  Resolution: player_pixel_color (render.odin).\n")
	fmt.sbprintf(&b, "player_form_frames := [Player_Form][2][FRAME_HEIGHT][FRAME_WIDTH]rune{{\n")
	for form_frames, form in frames {
		fmt.sbprintf(&b, "\t.%v = {{\n", form)
		for frame, fi in form_frames {
			notes_write(&b, notes, "pform", fmt.tprintf("%v_%d", form, fi), "\t\t")
			fmt.sbprintf(&b, "\t\t{{\n")
			for row in frame {
				fmt.sbprintf(&b, "\t\t\t{{")
				for ch, x in row {
					fmt.sbprintf(&b, "%s'%c'", x > 0 ? "," : "", ch)
				}
				fmt.sbprintf(&b, "}},\n")
			}
			fmt.sbprintf(&b, "\t\t}},\n")
		}
		fmt.sbprintf(&b, "\t}},\n")
	}
	fmt.sbprintf(&b, "}}\n")

	return strings.to_string(b)
}

// ─── gen_recipes.odin ─────────────────────────────────────────────────────────

emit_recipes :: proc(notes: ^Notes, recipes: []game.Recipe, unlock: ^[game.Item]game.Item, smelts: []game.Smelt_Rule, pending: []Pending_Item, allocator := context.allocator) -> string {
	b: strings.Builder
	strings.builder_init(&b, allocator)

	fmt.sbprintf(&b, "package game\n\n%s\n", GEN_HEADER)

	fmt.sbprintf(&b, "// The crafting table.  APPEND-ONLY: recipe indices are load-bearing for\n")
	fmt.sbprintf(&b, "// tests — never insert, delete or reorder rows.  Types and craft logic live\n")
	fmt.sbprintf(&b, "// in crafting.odin.\n")
	fmt.sbprintf(&b, "@(rodata)\nrecipe_table := [?]Recipe{{\n")
	for r in recipes {
		notes_write(&b, notes, "recipe", fmt.tprintf("%v", r.result), "\t")
		fmt.sbprintf(&b, "\t{{ .%v, %d, .%v, {{%s, %s, %s}} }},\n",
			r.result, r.result_count, r.station,
			ingredient_str(r.ingredients[0]),
			ingredient_str(r.ingredients[1]),
			ingredient_str(r.ingredients[2]))
	}
	for p in pending {
		if !p.has_recipe do continue
		fmt.sbprintf(&b, "\t{{ .%s, %d, .%v, {{%s, %s, %s}} }},\n",
			p.ident, p.result_count, p.station,
			ingredient_str(p.ings[0]), ingredient_str(p.ings[1]), ingredient_str(p.ings[2]))
	}
	fmt.sbprintf(&b, "}}\n\n")

	fmt.sbprintf(&b, "// Recipe unlock tree: a recipe stays hidden until the player first holds its\n")
	fmt.sbprintf(&b, "// gating material — keyed by the recipe's (unique) RESULT item; absent\n")
	fmt.sbprintf(&b, "// (= .None) means known from the start.  The unlock is STICKY\n")
	fmt.sbprintf(&b, "// (Progression_State.recipe_unlocked): once held, available forever.\n")
	fmt.sbprintf(&b, "// Tuning the pace of the early game = editing this table.\n")
	fmt.sbprintf(&b, "@(rodata)\nrecipe_unlock := #partial [Item]Item{{\n")
	emitted: [game.Item]bool
	for r in recipes {
		if emitted[r.result] do continue
		emitted[r.result] = true
		gate := unlock[r.result]
		if gate == .None do continue
		notes_write(&b, notes, "unlock", fmt.tprintf("%v", r.result), "\t")
		fmt.sbprintf(&b, "\t.%v = .%v,\n", r.result, gate)
	}
	for gate, it in unlock {
		// Defensive: gates on items that are not recipe results still emit.
		if gate == .None || emitted[it] do continue
		notes_write(&b, notes, "unlock", fmt.tprintf("%v", it), "\t")
		fmt.sbprintf(&b, "\t.%v = .%v,\n", it, gate)
	}
	for p in pending {
		if !p.has_recipe || p.unlock == .None do continue
		fmt.sbprintf(&b, "\t.%s = .%v,\n", p.ident, p.unlock)
	}
	fmt.sbprintf(&b, "}}\n\n")

	fmt.sbprintf(&b, "// What a smelter eats and what it casts.  New smeltable = new row.\n")
	fmt.sbprintf(&b, "// Smelt_Rule and the smelter logic live in sim.odin.\n")
	fmt.sbprintf(&b, "@(rodata)\nsmelt_table := [?]Smelt_Rule{{\n")
	for r in smelts {
		notes_write(&b, notes, "smelt", fmt.tprintf("%v", r.ore), "\t")
		fmt.sbprintf(&b, "\t{{ .%v, .%v, %d }},\n", r.ore, r.bar, r.ore_per_bar)
	}
	fmt.sbprintf(&b, "}}\n")

	return strings.to_string(b)
}

// ─── gen_terrain.odin ─────────────────────────────────────────────────────────

emit_terrain :: proc(notes: ^Notes, behavior: ^[game.Tile_Type]game.Terrain_Behavior, desc: ^[game.Tile_Type]string, is_struct: ^[game.Tile_Type]bool, glow: ^[game.Tile_Type]rl.Color, allocator := context.allocator) -> string {
	b: strings.Builder
	strings.builder_init(&b, allocator)

	fmt.sbprintf(&b, "package game\n\nimport rl \"vendor:raylib\"\n\n%s\n", GEN_HEADER)

	fmt.sbprintf(&b, "// One behavior row per tile: name / flags / color / move_cost /\n")
	fmt.sbprintf(&b, "// damage_per_second / drop_item / drop_pct (Terrain_Behavior in world.odin).\n")
	fmt.sbprintf(&b, "@(rodata)\nterrain_table := #partial [Tile_Type]Terrain_Behavior{{\n")
	for r, t in behavior {
		notes_write(&b, notes, "tile", fmt.tprintf("%v", t), "\t")
		fmt.sbprintf(&b, "\t.%v = {{ \"%s\", %s, %s, %s, %s, .%v, %d }},\n",
			t,
			escape_odin_string(r.name, context.temp_allocator),
			terrain_flags_str(r.flags),
			color_str(r.color),
			f32_str(r.move_cost),
			f32_str(r.damage_per_second),
			r.drop_item,
			r.drop_pct)
	}
	fmt.sbprintf(&b, "}}\n\n")

	fmt.sbprintf(&b, "// One line of \"what am I pointing at\" prose per tile, read by the cursor hover\n")
	fmt.sbprintf(&b, "// label (ui.odin).  Sparse on purpose: a tile that mines into an item already\n")
	fmt.sbprintf(&b, "// has that item's crafting-panel desc, so only tiles that drop nothing — or\n")
	fmt.sbprintf(&b, "// whose drop reads wrong for the tile in the ground — get their own line.\n")
	fmt.sbprintf(&b, "// tile_desc (world.odin) resolves the two; the tests keep every tile covered.\n")
	fmt.sbprintf(&b, "@(rodata)\nterrain_desc := #partial [Tile_Type]string{{\n")
	for d, t in desc {
		if d == "" do continue
		notes_write(&b, notes, "tiledesc", fmt.tprintf("%v", t), "\t")
		fmt.sbprintf(&b, "\t.%v = \"%s\",\n", t, escape_odin_string(d, context.temp_allocator))
	}
	fmt.sbprintf(&b, "}}\n\n")

	fmt.sbprintf(&b, "// Player-built machines, stations, spawners and altars — tiles you interact\n")
	fmt.sbprintf(&b, "// with, not terrain you dig.  A wand never fires at one (mining.odin): you\n")
	fmt.sbprintf(&b, "// reclaim a structure with the pick up close, which spills its contents safely.\n")
	fmt.sbprintf(&b, "@(rodata)\nis_structure_tile := #partial [Tile_Type]bool{{\n")
	for sv, t in is_struct {
		if !sv do continue
		notes_write(&b, notes, "struct", fmt.tprintf("%v", t), "\t")
		fmt.sbprintf(&b, "\t.%v = true,\n", t)
	}
	fmt.sbprintf(&b, "}}\n\n")

	fmt.sbprintf(&b, "// Stations read as magical in-world: a dark base, a breathing glow in the\n")
	fmt.sbprintf(&b, "// station's color, and the same pixel-art icon the bag shows.  Zero alpha\n")
	fmt.sbprintf(&b, "// (absent) = not a station.  update_ambience also reads this table to shed\n")
	fmt.sbprintf(&b, "// rising sparks off station tiles.\n")
	fmt.sbprintf(&b, "@(rodata)\nstation_glow := #partial [Tile_Type]rl.Color{{\n")
	for c, t in glow {
		if c == {} do continue
		notes_write(&b, notes, "glow", fmt.tprintf("%v", t), "\t")
		fmt.sbprintf(&b, "\t.%v = %s,\n", t, color_str(c))
	}
	fmt.sbprintf(&b, "}}\n")

	return strings.to_string(b)
}
