package game

// GENERATED by tools/gnipa_studio — do not hand-edit.
// Edit through the studio (or re-run gnipa_studio --extract) and this file is
// rewritten wholesale; row comments live in tools/gnipa_studio/notes.txt.
// Verify with: gnipa_studio --emit-check

// 16x22 ascii sprites, two walk frames each, shading baked into the art
// (light from above, near-black 'x' outline everywhere).  Legend: h/H/L
// clothing shadow/mid/rim and y/Y hair shadow/mid (player-tinted); k/K skin,
// m/M/N steel, f/F fur, b/B leather, w/W bone, s/S stone (shadow/mid, N =
// highlight); v void/black cloth, E eye glow, O/Q orb core/halo, G/g glowing
// core/ember ring, T gold trim.  Resolution: player_pixel_color (render.odin).
player_form_frames := [Player_Form][2][FRAME_HEIGHT][FRAME_WIDTH]rune{
	.Wizard = {
		// frame 0 — idle, orb held out
		{
			{' ',' ',' ',' ',' ',' ',' ','x','x',' ',' ',' ',' ',' ',' ',' '},
			{' ',' ',' ',' ',' ','x','x','H','x','x',' ',' ',' ',' ',' ',' '},
			{' ',' ',' ',' ','x','H','H','v','v','v','x',' ',' ',' ',' ',' '},
			{' ',' ',' ','x','H','H','v','v','v','v','x',' ',' ',' ',' ',' '},
			{' ',' ',' ',' ','x','H','v','v','v','v','v','x',' ',' ',' ',' '},
			{' ',' ',' ','x','H','H','v','v','v','v','v','v','x',' ',' ',' '},
			{' ',' ','x','H','H','v','v','v','v','v','v','v','v','x',' ',' '},
			{' ',' ','x','H','v','v','v','v','v','v','v','v','v','x',' ',' '},
			{' ',' ','x','h','v','v','v','v','v','v','v','v','v','v','x',' '},
			{' ',' ','x','h','v','v','v','v','v','v','v','v','v','v','x',' '},
			{' ','Q','x','h','v','v','v','v','v','v','v','v','v','v','x',' '},
			{'Q','O','Q','x','v','v','v','v','v','v','v','v','v','v','v','x'},
			{' ','Q',' ','x','h','v','v','v','v','v','v','v','v','v','x',' '},
			{' ',' ',' ','x','H','v','v','v','v','v','v','v','x',' ',' ',' '},
			{' ',' ','x','H','H','v','v','v','v','v','v','v','v','x',' ',' '},
			{' ','x','H','H','H','v','v','v','v','v','v','v','v','v','x',' '},
			{' ','x','H','H','H','v','v','v','v','v','v','v','v','v','x',' '},
			{'x','H','H','H','H','v','v','v','v','v','v','v','v','v','v','x'},
			{'x','H','H','H','v','v','v','v','v','v','v','v','v','v','v','x'},
			{' ','x','H','H','v','v','v','v','v','v','v','v','v','v','x',' '},
			{' ',' ','x','h','h','v','v','v','v','v','v','v','v','x',' ',' '},
			{' ',' ',' ','x','x','x',' ',' ','x','x','x',' ',' ',' ',' ',' '},
		},
		// frame 1 — mid-stride, hem sways
		{
			{' ',' ',' ',' ',' ',' ',' ','x','x',' ',' ',' ',' ',' ',' ',' '},
			{' ',' ',' ',' ',' ','x','x','H','x','x',' ',' ',' ',' ',' ',' '},
			{' ',' ',' ',' ','x','H','H','v','v','v','x',' ',' ',' ',' ',' '},
			{' ',' ',' ','x','H','H','v','v','v','v','x',' ',' ',' ',' ',' '},
			{' ',' ',' ',' ','x','H','v','v','v','v','v','x',' ',' ',' ',' '},
			{' ',' ',' ','x','H','H','v','v','v','v','v','v','x',' ',' ',' '},
			{' ',' ','x','H','H','v','v','v','v','v','v','v','v','x',' ',' '},
			{' ',' ','x','H','v','v','v','v','v','v','v','v','v','x',' ',' '},
			{' ',' ','x','h','v','v','v','v','v','v','v','v','v','v','x',' '},
			{' ',' ','x','h','v','v','v','v','v','v','v','v','v','v','x',' '},
			{' ','Q','x','h','v','v','v','v','v','v','v','v','v','v','x',' '},
			{'Q','O','Q','x','v','v','v','v','v','v','v','v','v','v','v','x'},
			{' ','Q',' ','x','h','v','v','v','v','v','v','v','v','v','x',' '},
			{' ',' ',' ','x','H','v','v','v','v','v','v','v','x',' ',' ',' '},
			{' ',' ','x','H','H','v','v','v','v','v','v','v','v','x',' ',' '},
			{' ','x','H','H','H','v','v','v','v','v','v','v','v','v','x',' '},
			{' ','x','H','H','H','v','v','v','v','v','v','v','v','v','x',' '},
			{'x','H','H','H','H','v','v','v','v','v','v','v','v','v','v','x'},
			{'x','H','H','H','v','v','v','v','v','v','v','v','v','v','v','x'},
			{' ','x','H','H','v','v','v','v','v','v','v','v','v','v','x',' '},
			{' ','x','h','h','v','v','v','v','v','v','v','v','v','v','x',' '},
			{' ',' ','x','x','x',' ',' ',' ',' ',' ','x','x','x',' ',' ',' '},
		},
	},
}
