package game

import rl "vendor:raylib"

// GENERATED by tools/gnipa_studio — do not hand-edit.
// Edit through the studio (or re-run gnipa_studio --extract) and this file is
// rewritten wholesale; row comments live in tools/gnipa_studio/notes.txt.
// Verify with: gnipa_studio --emit-check

// One behavior row per tile: name / flags / color / move_cost /
// damage_per_second / drop_item / drop_pct (Terrain_Behavior in world.odin).
@(rodata)
terrain_table := [Tile_Type]Terrain_Behavior{
	.Air = { "Air", {}, {135, 206, 235, 255}, 1, 0, .None, 0 },
	.Void = { "Void", {}, {0, 0, 0, 255}, 1, 0, .None, 0 },
	.Grass = { "Grass", {.Solid, .Mineable}, {34, 139, 34, 255}, 0, 0, .Grass_Turf, 0 },
	// Natural cave stone never moves; but a PLACED stone block obeys gravity
	// and re-stacks sand-style — .Falls_Placed gates it on the cell's .Placed
	// bit so only player-built stone falls.
	.Stone = { "Stone", {.Solid, .Mineable, .Falls_Placed, .Settles}, {128, 128, 128, 255}, 0, 0, .Stone_Block, 0 },
	.Water = { "Water", {.Walkable, .Swimmable}, {30, 100, 200, 200}, 2, 0, .None, 0 },
	.Lava = { "Lava", {.Walkable, .Damaging}, {220, 80, 0, 255}, 2, 2, .None, 0 },
	.Magic_Lava = { "Magic Lava", {.Walkable, .Damaging}, {160, 0, 220, 255}, 2, 4, .None, 0 },
	.Wood = { "Wood", {.Solid, .Flammable, .Mineable, .Falls}, {139, 90, 43, 255}, 0, 0, .Wood_Log, 0 },
	.Leaves = { "Leaves", {.Walkable, .Flammable, .Mineable, .Falls}, {0, 180, 0, 200}, 1, 0, .Leaf, 0 },
	.Iron_Ore = { "Iron Ore", {.Solid, .Mineable}, {180, 130, 100, 255}, 0, 0, .Iron_Ore, 0 },
	.Silver_Ore = { "Silver Ore", {.Solid, .Mineable}, {200, 200, 220, 255}, 0, 0, .Silver_Ore, 0 },
	.Gold_Ore = { "Gold Ore", {.Solid, .Mineable}, {220, 180, 0, 255}, 0, 0, .Gold_Ore, 0 },
	.Gold_Rare_Ore = { "Rare Gold Ore", {.Solid, .Mineable}, {255, 215, 50, 255}, 0, 0, .Gold_Rare_Ore, 0 },
	.Crafting_Bench = { "Crafting Bench", {.Solid, .Mineable, .Placeable}, {160, 120, 60, 255}, 0, 0, .Crafting_Bench, 0 },
	.Tree_Grower = { "Tree Grower", {.Solid, .Mineable, .Placeable}, {0, 140, 0, 255}, 0, 0, .Tree_Grower, 0 },
	.Smelter = { "Smelter", {.Solid, .Mineable, .Placeable}, {200, 100, 0, 255}, 0, 0, .Smelter, 0 },
	.Cave_Entrance = { "Cave Entrance", {.Walkable}, {60, 0, 80, 255}, 1, 0, .None, 0 },
	.Sky_Entrance = { "Sky Entrance", {.Walkable}, {180, 220, 255, 255}, 1, 0, .None, 0 },
	.Sky_Altar = { "Sky Altar", {.Solid, .Mineable, .Placeable}, {200, 200, 255, 255}, 0, 0, .Sky_Altar, 0 },
	.Cloud = { "Cloud", {.Solid, .Mineable}, {240, 240, 255, 200}, 0, 0, .Cloud_Stone, 20 },
	.Cloud_Ore = { "Cloud Ore", {.Solid, .Mineable}, {200, 220, 255, 255}, 0, 0, .Cloud_Stone, 0 },
	.Aether_Ore = { "Aether Ore", {.Solid, .Mineable}, {180, 255, 200, 255}, 0, 0, .Aether_Crystal, 0 },
	.Runic_Sky_Ore = { "Runic Sky Ore", {.Solid, .Mineable}, {255, 180, 255, 255}, 0, 0, .Runic_Sky_Ore, 0 },
	.Wind_Current = { "Wind Current", {.Walkable}, {200, 240, 255, 150}, 1, 0, .None, 0 },
	.Void_Sky = { "Void Sky", {.Walkable, .Damaging}, {0, 0, 0, 255}, 1, 1, .None, 0 },
	.Flower = { "Flower", {.Walkable}, {255, 220, 50, 255}, 1, 0, .None, 0 },
	.Dvergr_Forge = { "Dvergr Forge", {.Solid, .Mineable, .Placeable}, {105, 105, 125, 255}, 0, 0, .Dvergr_Forge, 0 },
	.Rune_Altar = { "Rune Altar", {.Solid, .Mineable, .Placeable}, {150, 90, 220, 255}, 0, 0, .Rune_Altar, 0 },
	.Dimension_Spawner = { "Metal Dimension Spawner", {.Solid, .Mineable, .Placeable}, {40, 200, 180, 255}, 0, 0, .Dimension_Spawner, 0 },
	.Dimension_Gate = { "Dimension Gate", {.Walkable}, {30, 140, 130, 255}, 1, 0, .None, 0 },
	.Dimension_Spawner_Gold = { "Gold Dimension Spawner", {.Solid, .Mineable, .Placeable}, {235, 195, 60, 255}, 0, 0, .Dimension_Spawner_Gold, 0 },
	.Emerald_Ore = { "Emerald Ore", {.Solid, .Mineable}, {50, 205, 120, 255}, 0, 0, .Emerald, 0 },
	.Jade_Ore = { "Jade Ore", {.Solid, .Mineable}, {150, 210, 165, 255}, 0, 0, .Jade, 0 },
	.Diamond_Ore = { "Diamond Ore", {.Solid, .Mineable}, {190, 235, 255, 255}, 0, 0, .Diamond, 0 },
	.Hel_Gem_Ore = { "Hel Gem Ore", {.Solid, .Mineable}, {200, 30, 70, 255}, 0, 0, .Hel_Gem, 0 },
	.Auto_Miner = { "Auto-Miner", {.Solid, .Mineable, .Placeable}, {90, 200, 190, 255}, 0, 0, .Auto_Miner, 0 },
	.Miner_Body = { "Miner Body", {.Solid, .Mineable}, {120, 128, 140, 255}, 0, 0, .None, 0 },
	.Dimension_Spawner_Runic = { "Runic Dimension Spawner", {.Solid, .Mineable, .Placeable}, {200, 120, 255, 255}, 0, 0, .Dimension_Spawner_Runic, 0 },
	.Silo = { "Silo", {.Solid, .Mineable, .Placeable}, {140, 150, 165, 255}, 0, 0, .Silo, 0 },
	// A building block (like Stone/Grass, not a machine) that obeys gravity:
	// always player-placed, so .Falls is safe, and .Settles makes it stack
	// as tiles when it lands (sand-style) rather than crumble to drops.
	// Mines back into the Dirt item.
	.Dirt = { "Dirt", {.Solid, .Mineable, .Falls, .Settles}, {120, 84, 50, 255}, 0, 0, .Dirt, 0 },
	// Statically solid + mineable; a cell flagged .Open is passable (that
	// override lives in door_open / is_solid / gravity).  Mines to a Door.
	.Door = { "Door", {.Solid, .Mineable}, {150, 100, 55, 255}, 0, 0, .Door, 0 },
	// A planted crop: walkable like a wild flower, harvested by walking
	// through it (player_pickup), not mined — so no drop_item.
	.Flower_Bed = { "Flower Bed", {.Walkable}, {120, 90, 50, 255}, 1, 0, .None, 0 },
	// A placed chest, mined back for its item like any machine (an empty
	// one — a loaded barrel refuses the pick, guarded in events.odin).
	.Barrel = { "Barrel", {.Solid, .Mineable, .Placeable}, {150, 100, 55, 255}, 0, 0, .Barrel, 0 },
	// The four sealed coffers are .Mineable only so the deliberate Shift+hold
	// reclaim can prise them loose once emptied — a wand never strikes them and
	// an ordinary click still opens them (both gated by is_structure_tile).
	// They all reclaim into one plain Rune_Coffer: the tier seal is a one-time
	// in-situ marking, not something you carry around.
	.Sky_Rune_Scroll_Chest = { "Sky Rune Scroll Chest", {.Solid, .Mineable}, {120, 200, 255, 255}, 0, 0, .Rune_Coffer, 0 },
	.Rune_Scroll_Chest_A = { "Bronze Rune Scroll Chest", {.Solid, .Mineable}, {182, 108, 58, 255}, 0, 0, .Rune_Coffer, 0 },
	.Rune_Scroll_Chest_B = { "Silver Rune Scroll Chest", {.Solid, .Mineable}, {205, 205, 225, 255}, 0, 0, .Rune_Coffer, 0 },
	.Rune_Scroll_Chest_C = { "Golden Rune Scroll Chest", {.Solid, .Mineable}, {235, 195, 60, 255}, 0, 0, .Rune_Coffer, 0 },
	.Clay = { "Clay", {.Solid, .Mineable, .Falls_Placed, .Settles}, {166, 105, 72, 255}, 0, 0, .Clay, 0 },
	.Clay_Hearth = { "Clay Hearth", {.Solid}, {180, 105, 58, 255}, 0, 0, .None, 0 },
	.Golem_Depot = { "Golem Depot", {.Solid}, {82, 145, 118, 255}, 0, 0, .None, 0 },
	.World_Anchor = { "World Anchor", {.Solid}, {145, 78, 190, 255}, 0, 0, .None, 0 },
	// Solid to everyone, but deliberately NOT .Mineable — it never yields
	// material and is never reclaimed by mining. It only ever disappears via
	// golem.odin's own despawn sweep (golem_dissolve_quick_clay).
	.Quick_Clay = { "Quick Clay", {.Solid}, {196, 150, 118, 255}, 0, 0, .None, 0 },
	.Sand = { "Sand", {.Solid, .Mineable}, {225, 205, 150, 255}, 0, 0, .Sand, 0 },
	// The carried coffer, re-placed: ordinary barrel storage in the chest's
	// own silhouette, its lock lit dull rune-stone instead of a tier color.
	.Rune_Coffer = { "Rune Coffer", {.Solid, .Mineable, .Placeable}, {150, 138, 120, 255}, 0, 0, .Rune_Coffer, 0 },
	// The first gas.  This row is where a craft track's vapour effect lives:
	// steam scalds via damage_per_second, read generically by the hazard pass.
	.Steam = { "Steam", {.Walkable, .Damaging}, {225, 228, 235, 110}, 1, 2, .None, 0 },
	.Boiler = { "Boiler", {.Solid, .Mineable, .Placeable}, {96, 102, 116, 255}, 0, 0, .Boiler, 0 },
	.Steam_Engine = { "Steam Engine", {.Solid, .Mineable, .Placeable}, {150, 122, 62, 255}, 0, 0, .Steam_Engine, 0 },
	.Gem_Replicator = { "Gem Replicator", {.Solid, .Mineable, .Placeable}, {168, 120, 205, 255}, 0, 0, .Gem_Replicator, 0 },
	.Green_Cave_Mushroom = { "Green Cave Mushroom", {.Walkable, .Mineable}, {80, 190, 85, 255}, 1, 0, .Green_Cave_Mushroom, 0 },
}

// One line of "what am I pointing at" prose per tile, read by the cursor hover
// label (ui.odin).  Sparse on purpose: a tile that mines into an item already
// has that item's crafting-panel desc, so only tiles that drop nothing — or
// whose drop reads wrong for the tile in the ground — get their own line.
// tile_desc (world.odin) resolves the two; the tests keep every tile covered.
@(rodata)
terrain_desc := #partial [Tile_Type]string{
	.Air = "Open air — nothing here to mine.",
	.Void = "Unbroken dark. Nothing lives in it and nothing digs out of it.",
	.Grass = "Turf-capped surface soil. Mines into a placeable square of turf.",
	.Water = "Swimmable water — it slows you down. Scoop it with an iron bucket.",
	.Lava = "Molten rock. It burns while you stand in it; an iron bucket moves it.",
	.Magic_Lava = "Cursed molten rock — it burns far harder than plain lava.",
	// Gateways: the label should say where the step leads.
	.Cave_Entrance = "A mouth into the caves. Walk into it to descend.",
	.Sky_Entrance = "A gate to the low sky. Walk into it to rise.",
	// Sky
	.Cloud = "A drifting cloud bank. Mining it sheds cloud stone now and then.",
	.Wind_Current = "A ribbon of moving air threading the sky.",
	.Void_Sky = "The sky's raw edge. It bleeds you for every moment you hang in it.",
	// Crops: harvested by walking through, never mined, so they drop nothing.
	.Flower = "A wild bloom. Walk through it to forage the flower.",
	.Dimension_Gate = "The way out of a manufactured world. Walk in to return.",
	// The auto-miner's tail, mineable but yielding nothing.
	.Miner_Body = "The auto-miner's spent trail. Mine it away to clear the line.",
	.Flower_Bed = "A planted crop. Walk through it to harvest whatever has bloomed.",
	// Sealed coffers: the Rune Coffer drop line describes the emptied husk, not
	// the sealed chest you are looking at.
	.Sky_Rune_Scroll_Chest = "A sealed sky coffer. Open it to take the scroll inside.",
	.Rune_Scroll_Chest_A = "A sealed bronze coffer. Open it to take the scroll inside.",
	.Rune_Scroll_Chest_B = "A sealed silver coffer. Open it to take the scroll inside.",
	.Rune_Scroll_Chest_C = "A sealed golden coffer. Open it to take the scroll inside.",
	// Golem monuments — solid, unmineable, each with its own job.
	.Clay_Hearth = "The crew's hearth: mends a cracked golem for clay, and binds a better command wand.",
	.Golem_Depot = "The crew's drop-off. Deployed golems stock it; press E to empty it into your bag.",
	.World_Anchor = "Holds a manufactured world in place so it survives you leaving it.",
	.Quick_Clay = "A foothold a golem conjured for itself. It dissolves on its own.",
	.Steam = "Scalding vapour. It rises, it leaks, and it fades - cap your chamber or lose your pressure.",
}

// Player-built machines, stations, spawners and altars — tiles you interact
// with, not terrain you dig.  A wand never fires at one (mining.odin): you
// reclaim a structure with the pick up close, which spills its contents safely.
@(rodata)
is_structure_tile := #partial [Tile_Type]bool{
	.Crafting_Bench = true,
	.Tree_Grower = true,
	.Smelter = true,
	.Sky_Altar = true,
	.Dvergr_Forge = true,
	.Rune_Altar = true,
	.Dimension_Spawner = true,
	.Dimension_Spawner_Gold = true,
	.Auto_Miner = true,
	.Dimension_Spawner_Runic = true,
	.Silo = true,
	.Barrel = true,
	// Coffers are equipment too: a wand must never strike one, an ordinary
	// click opens it, and only the deliberate Shift+hold prises it loose.
	// (Input routes the four sealed variants to their own open path first.)
	.Sky_Rune_Scroll_Chest = true,
	.Rune_Scroll_Chest_A = true,
	.Rune_Scroll_Chest_B = true,
	.Rune_Scroll_Chest_C = true,
	.Clay_Hearth = true,
	.Golem_Depot = true,
	.World_Anchor = true,
	.Rune_Coffer = true,
	.Boiler = true,
	.Steam_Engine = true,
	.Gem_Replicator = true,
}

// Stations read as magical in-world: a dark base, a breathing glow in the
// station's color, and the same pixel-art icon the bag shows.  Zero alpha
// (absent) = not a station.  update_ambience also reads this table to shed
// rising sparks off station tiles.
@(rodata)
station_glow := #partial [Tile_Type]rl.Color{
	// hearth gold
	.Crafting_Bench = {255, 200, 90, 255},
	// living green
	.Tree_Grower = {110, 230, 110, 255},
	// furnace ember
	.Smelter = {255, 120, 30, 255},
	// sky blue
	.Sky_Altar = {130, 200, 255, 255},
	// forge fire
	.Dvergr_Forge = {255, 150, 60, 255},
	// rune purple
	.Rune_Altar = {190, 120, 255, 255},
	// dimensional teal
	.Dimension_Spawner = {80, 255, 220, 255},
	// gilded shimmer
	.Dimension_Spawner_Gold = {255, 225, 100, 255},
	// the snake's beating heart
	.Auto_Miner = {120, 255, 210, 255},
	// runic violet
	.Dimension_Spawner_Runic = {210, 140, 255, 255},
	// cold iron sheen
	.Silo = {200, 210, 225, 255},
	// warm oak
	.Barrel = {190, 140, 80, 255},
	// steam white
	.Boiler = {200, 225, 240, 255},
	// working brass
	.Steam_Engine = {235, 200, 110, 255},
	// prismatic violet-white
	.Gem_Replicator = {215, 170, 255, 255},
}
