package game

// GENERATED by tools/gnipa_studio — do not hand-edit.
// Edit through the studio (or re-run gnipa_studio --extract) and this file is
// rewritten wholesale; row comments live in tools/gnipa_studio/notes.txt.
// Verify with: gnipa_studio --emit-check

// The crafting table.  APPEND-ONLY: recipe indices are load-bearing for
// tests — never insert, delete or reorder rows.  Types and craft logic live
// in crafting.odin.
@(rodata)
recipe_table := [?]Recipe{
	{ .Plank, 4, .None, {{.Wood_Log, 1}, {}, {}} },
	{ .Crafting_Bench, 1, .None, {{.Plank, 4}, {}, {}} },
	{ .Smelter, 1, .Bench, {{.Stone_Block, 8}, {.Iron_Ore, 2}, {}} },
	{ .Tree_Grower, 1, .Bench, {{.Plank, 2}, {.Leaf, 4}, {}} },
	{ .Iron_Bucket, 1, .Bench, {{.Iron_Bar, 3}, {}, {}} },
	{ .Sky_Altar, 1, .Bench, {{.Stone_Block, 6}, {.Plank, 4}, {}} },
	{ .Sword, 1, .Bench, {{.Iron_Bar, 2}, {.Plank, 1}, {}} },
	// The station ladder: forge is smithed at the bench from smelted iron,
	// the altar raised at the forge — its cloud stone means reaching the sky
	// first.  Forge-tier and up runs on bars: the smelter casts them from
	// ore stacks dropped beside it (1 iron ore = 1 bar; silver/gold 2 = 1).
	{ .Dvergr_Forge, 1, .Bench, {{.Stone_Block, 10}, {.Iron_Bar, 3}, {}} },
	{ .Rune_Altar, 1, .Forge, {{.Gold_Bar, 2}, {.Cloud_Stone, 6}, {}} },
	// The miner's ladder: each wand tier consumes the one before it.
	{ .Mine_Wand, 1, .Bench, {{.Plank, 2}, {.Iron_Ore, 4}, {}} },
	{ .Mine_Wand_Silver, 1, .Forge, {{.Mine_Wand, 1}, {.Silver_Bar, 3}, {}} },
	{ .Mine_Wand_Gold, 1, .Forge, {{.Mine_Wand_Silver, 1}, {.Gold_Bar, 3}, {}} },
	// Weapon ladder — same pattern as the wands.
	{ .Silver_Sword, 1, .Forge, {{.Sword, 1}, {.Silver_Bar, 3}, {}} },
	{ .Gold_Sword, 1, .Forge, {{.Silver_Sword, 1}, {.Gold_Bar, 3}, {}} },
	// Armor: forge iron pieces, then upgrade each through silver into gold
	// (right-click a piece in the bag to wear it).
	{ .Iron_Helm, 1, .Bench, {{.Iron_Bar, 3}, {.Plank, 1}, {}} },
	{ .Iron_Chestplate, 1, .Bench, {{.Iron_Bar, 5}, {.Plank, 2}, {}} },
	{ .Iron_Gauntlets, 1, .Bench, {{.Iron_Bar, 2}, {.Plank, 1}, {}} },
	{ .Iron_Greaves, 1, .Bench, {{.Iron_Bar, 4}, {.Plank, 1}, {}} },
	{ .Iron_Boots, 1, .Bench, {{.Iron_Bar, 2}, {.Plank, 1}, {}} },
	{ .Silver_Helm, 1, .Forge, {{.Iron_Helm, 1}, {.Silver_Bar, 2}, {}} },
	{ .Silver_Chestplate, 1, .Forge, {{.Iron_Chestplate, 1}, {.Silver_Bar, 3}, {}} },
	{ .Silver_Gauntlets, 1, .Forge, {{.Iron_Gauntlets, 1}, {.Silver_Bar, 2}, {}} },
	{ .Silver_Greaves, 1, .Forge, {{.Iron_Greaves, 1}, {.Silver_Bar, 3}, {}} },
	{ .Silver_Boots, 1, .Forge, {{.Iron_Boots, 1}, {.Silver_Bar, 2}, {}} },
	{ .Gold_Helm, 1, .Forge, {{.Silver_Helm, 1}, {.Gold_Bar, 2}, {}} },
	{ .Gold_Chestplate, 1, .Forge, {{.Silver_Chestplate, 1}, {.Gold_Bar, 3}, {}} },
	{ .Gold_Gauntlets, 1, .Forge, {{.Silver_Gauntlets, 1}, {.Gold_Bar, 2}, {}} },
	{ .Gold_Greaves, 1, .Forge, {{.Silver_Greaves, 1}, {.Gold_Bar, 3}, {}} },
	{ .Gold_Boots, 1, .Forge, {{.Silver_Boots, 1}, {.Gold_Bar, 2}, {}} },
	// Trinkets
	{ .Aether_Charm, 1, .Rune_Altar, {{.Aether_Crystal, 3}, {.Gold_Bar, 1}, {}} },
	// Bulk storage: the first machine that counts past 99 (draft1 §7.6 step 1).
	// Q-drop stacks beside it to feed it; a smelter next door casts bars
	// straight in.
	{ .Silo, 1, .Forge, {{.Stone_Block, 20}, {.Iron_Bar, 4}, {}} },
	// Parallel dimensions: the metal you pay is the metal the world is rich
	// in — each theme's recipe mirrors its riches.
	{ .Dimension_Spawner, 1, .Rune_Altar, {{.Iron_Bar, 4}, {.Cloud_Stone, 8}, {.Stone_Block, 20}} },
	{ .Dimension_Spawner_Gold, 1, .Rune_Altar, {{.Gold_Bar, 4}, {.Cloud_Stone, 8}, {.Stone_Block, 20}} },
	// The endgame sink: 500 bars is roughly a strip-mined Gold world — one
	// whole dimension traded for the door to the runic tier.
	{ .Dimension_Spawner_Runic, 1, .Rune_Altar, {{.Gold_Bar, 500}, {.Cloud_Stone, 20}, {}} },
	// The snake miner: strips a dimension on its own.  The emerald is the
	// first gem sink — nature seeds the machine that industrializes worlds.
	{ .Auto_Miner, 1, .Rune_Altar, {{.Iron_Bar, 6}, {.Gold_Bar, 2}, {.Emerald, 1}} },
	// Runic tier: gold gear reforged with sky runes at the altar.
	{ .Mine_Wand_Runic, 1, .Rune_Altar, {{.Mine_Wand_Gold, 1}, {.Runic_Sky_Ore, 6}, {}} },
	{ .Runic_Sword, 1, .Rune_Altar, {{.Gold_Sword, 1}, {.Runic_Sky_Ore, 6}, {}} },
	{ .Runic_Helm, 1, .Rune_Altar, {{.Gold_Helm, 1}, {.Runic_Sky_Ore, 4}, {}} },
	{ .Runic_Chestplate, 1, .Rune_Altar, {{.Gold_Chestplate, 1}, {.Runic_Sky_Ore, 6}, {}} },
	{ .Runic_Gauntlets, 1, .Rune_Altar, {{.Gold_Gauntlets, 1}, {.Runic_Sky_Ore, 3}, {}} },
	{ .Runic_Greaves, 1, .Rune_Altar, {{.Gold_Greaves, 1}, {.Runic_Sky_Ore, 5}, {}} },
	{ .Runic_Boots, 1, .Rune_Altar, {{.Gold_Boots, 1}, {.Runic_Sky_Ore, 3}, {}} },
	// A 2-tall wooden door, buildable from the very first bench — E toggles it
	// open (walk through) or shut (solid).  One log's worth of planks.
	{ .Door, 1, .Bench, {{.Plank, 4}, {}, {}} },
	// Healing: surface flowers, foraged by walking through them, brew into a
	// Health Potion at the bench — early-game recovery.
	{ .Potion_Health, 1, .Bench, {{.Flower, 3}, {}, {}} },
	// Flower farming: sow seeds into a bed (with soil + a plank frame) — it
	// grows 5 flowers you harvest by walking through it.
	{ .Flower_Bed, 1, .Bench, {{.Dirt, 1}, {.Plank, 1}, {.Flower_Seed, 5}} },
	// Storage: a wooden 4×4 barrel — early overflow for a 24-slot bag.
	// Cheap on purpose (2 logs' worth of planks).
	{ .Barrel, 1, .Bench, {{.Plank, 8}, {}, {}} },
	// A recoverable trash buffer: the newest offered stack replaces and
	// permanently erases the previous one. Forged from all three tier-2 riches.
	{ .Void_Charm, 1, .Forge, {{.Silver_Bar, 4}, {.Gold_Bar, 2}, {.Emerald, 1}} },
	// Clay automation begins after the first cast iron.  Each worker is a
	// material investment; the Hearth upgrades the wand itself later.
	{ .Command_Wand, 1, .Bench, {{.Clay, 2}, {.Plank, 2}, {.Iron_Bar, 1}} },
	{ .Clay_Golem, 1, .Bench, {{.Clay, 4}, {.Iron_Bar, 1}, {}} },
	// A cheap early recall charm: forged at the bench with an iron bar and
	// a jade.  Worn in a charm slot, not spent — while equipped, the
	// inventory's "Return to Surface" button warps straight home.
	{ .Jade_Ring, 1, .Bench, {{.Iron_Bar, 1}, {.Jade, 1}, {}} },
	// Steam industry, machine one: the kettle.
	{ .Boiler, 1, .Bench, {{.Iron_Bar, 4}, {.Stone_Block, 6}, {}} },
	{ .Steam_Engine, 1, .Forge, {{.Iron_Bar, 10}, {.Silver_Bar, 2}, {}} },
	// The gem farm: gems appear in cave 1, but the Rune Altar needs Cloud
	// Stone (sky, post-ritual-A) — the farm is the industrialisation step.
	{ .Gem_Replicator, 1, .Rune_Altar, {{.Iron_Bar, 8}, {.Gold_Bar, 4}, {.Cloud_Stone, 10}} },
	{ .GreenBerrie, 1, .Bench, {{.Flower_Seed, 1}, {.Leaf, 1}, {.Green_Cave_Mushroom, 1}} },
	{ .Clay, 2, .None, {{.Stone_Block, 1}, {}, {}} },
	// Magic industry, the sink half: the kettle burns gems for power.
	{ .Magic_Kettle, 1, .Rune_Altar, {{.Iron_Bar, 6}, {.Gold_Bar, 3}, {.Cloud_Stone, 8}} },
	{ .Mana_Wheel, 1, .Forge, {{.Iron_Bar, 10}, {.Silver_Bar, 2}, {}} },
	{ .Mana_Pipe, 1, .Bench, {{.Iron_Bar, 2}, {.Cloud_Stone, 1}, {}} },
	// Ranged combat, rung one: a gem-hearted wand that throws fire orbs.
	// The emerald is the magic heart — combat wands are the gem economy's
	// martial sink, the way mine wands are the ore economy's.
	{ .Fire_Wand, 1, .Bench, {{.Plank, 2}, {.Iron_Ore, 2}, {.Emerald, 1}} },
}

// Recipe unlock tree: a recipe stays hidden until the player first holds its
// gating material — keyed by the recipe's (unique) RESULT item; absent
// (= .None) means known from the start.  The unlock is STICKY
// (Progression_State.recipe_unlocked): once held, available forever.
// Tuning the pace of the early game = editing this table.
@(rodata)
recipe_unlock := #partial [Item]Item{
	// Iron tier — reward for reaching the first ore
	.Smelter = .Iron_Ore,
	// Domestic tier — the moment you can work wood / forage
	.Tree_Grower = .Plank,
	.Iron_Bucket = .Iron_Bar,
	.Sky_Altar = .Stone_Block,
	.Sword = .Iron_Ore,
	// Smelted tier — opens once you cast your first bar.  The Jade Ring
	// shows up here too, ungated by Jade itself, so the recipe card (and its
	// Jade cost) is the player's cue to go look for the gem.
	.Dvergr_Forge = .Iron_Bar,
	// Sky tier
	.Rune_Altar = .Cloud_Stone,
	.Mine_Wand = .Iron_Ore,
	.Mine_Wand_Silver = .Silver_Bar,
	.Mine_Wand_Gold = .Gold_Bar,
	// Silver / gold ladders
	.Silver_Sword = .Silver_Bar,
	.Gold_Sword = .Gold_Bar,
	.Iron_Helm = .Iron_Bar,
	.Iron_Chestplate = .Iron_Bar,
	.Iron_Gauntlets = .Iron_Bar,
	.Iron_Greaves = .Iron_Bar,
	.Iron_Boots = .Iron_Bar,
	.Silver_Helm = .Silver_Bar,
	.Silver_Chestplate = .Silver_Bar,
	.Silver_Gauntlets = .Silver_Bar,
	.Silver_Greaves = .Silver_Bar,
	.Silver_Boots = .Silver_Bar,
	.Gold_Helm = .Gold_Bar,
	.Gold_Chestplate = .Gold_Bar,
	.Gold_Gauntlets = .Gold_Bar,
	.Gold_Greaves = .Gold_Bar,
	.Gold_Boots = .Gold_Bar,
	.Aether_Charm = .Aether_Crystal,
	.Silo = .Iron_Bar,
	.Dimension_Spawner = .Cloud_Stone,
	.Dimension_Spawner_Gold = .Gold_Bar,
	.Dimension_Spawner_Runic = .Gold_Bar,
	.Auto_Miner = .Emerald,
	// Runic endgame
	.Mine_Wand_Runic = .Runic_Sky_Ore,
	.Runic_Sword = .Runic_Sky_Ore,
	.Runic_Helm = .Runic_Sky_Ore,
	.Runic_Chestplate = .Runic_Sky_Ore,
	.Runic_Gauntlets = .Runic_Sky_Ore,
	.Runic_Greaves = .Runic_Sky_Ore,
	.Runic_Boots = .Runic_Sky_Ore,
	.Door = .Plank,
	.Potion_Health = .Flower,
	.Flower_Bed = .Flower_Seed,
	.Barrel = .Plank,
	.Void_Charm = .Emerald,
	.Command_Wand = .Clay,
	.Clay_Golem = .Command_Wand,
	.Jade_Ring = .Iron_Bar,
	.Boiler = .Iron_Bar,
	// power is a real mid-game gate
	.Steam_Engine = .Silver_Bar,
	// The card appears the moment you hold your first gem — it TELLS the
	// player the farm exists before the recipe is affordable.
	.Gem_Replicator = .Emerald,
	.GreenBerrie = .Leaf,
	// The card appears the moment you hold your first gem, same tell as the
	// Replicator; the wheel waits on the kettle existing, and the pipe on the
	// wheel - a built-in build order.
	.Magic_Kettle = .Emerald,
	.Mana_Wheel = .Magic_Kettle,
	.Mana_Pipe = .Mana_Wheel,
	// Same tell as the kettle: your first gem reveals the fire wand card.
	.Fire_Wand = .Emerald,
}

// What a smelter eats and what it casts.  New smeltable = new row.
// Smelt_Rule and the smelter logic live in sim.odin.
@(rodata)
smelt_table := [?]Smelt_Rule{
	{ .Iron_Ore, .Iron_Bar, 1 },
	{ .Silver_Ore, .Silver_Bar, 2 },
	{ .Gold_Ore, .Gold_Bar, 2 },
	// rare ore is rich: one is enough
	{ .Gold_Rare_Ore, .Gold_Bar, 1 },
}
