package game

// GENERATED by tools/gnipa_studio — do not hand-edit.
// Edit through the studio (or re-run gnipa_studio --extract) and this file is
// rewritten wholesale; row comments live in tools/gnipa_studio/notes.txt.
// Verify with: gnipa_studio --emit-check

// Shared 12x12 shape grids and tier palettes, then one Item_Icon per item.
// Legend and drawing live in item_art.odin (icon_pixel / draw_item_icon);
// which names exist here is mirrored by tools/gnipa_studio/registry.odin.

// Metal tiers, echoing the old flat item_table colors so gear stays readable.
PAL_IRON :: Icon_Palette{{150, 150, 165, 255}, {100, 100, 115, 255}, {198, 198, 212, 255}, {}, {}}
PAL_SILVER :: Icon_Palette{{205, 205, 225, 255}, {148, 148, 175, 255}, {242, 242, 252, 255}, {}, {}}
PAL_GOLD :: Icon_Palette{{235, 195, 60, 255}, {178, 138, 28, 255}, {255, 232, 130, 255}, {}, {}}
PAL_RUNIC :: Icon_Palette{{210, 130, 255, 255}, {148, 78, 200, 255}, {240, 195, 255, 255}, {}, {}}

SWORD_GRID :: Icon_Grid{
	"......L.....",
	"......LD....",
	"......LD....",
	"......LD....",
	"......LD....",
	"......LD....",
	"......LD....",
	".....gggg...",
	"......hh....",
	"......hh....",
	"......gg....",
	"............",
}

PICKAXE_GRID :: Icon_Grid{
	"..DBBBBBBD..",
	".BDDDhhDDDB.",
	".BD..hh..DB.",
	"DD...hh...DD",
	"D....hh....D",
	".....hh.....",
	".....hh.....",
	".....hh.....",
	".....hh.....",
	".....hh.....",
	"............",
	"............",
}

POTION_GRID :: Icon_Grid{
	".....hh.....",
	".....hh.....",
	"....DLLD....",
	"....DBBD....",
	"...DBBBBD...",
	"..DBBBBBBD..",
	"..DBWBBBBD..",
	"..DBBBBBBD..",
	"..DBBBBBBD..",
	"...DBBBBD...",
	"....DDDD....",
	"............",
}

// A scatter of seeds — each a body pixel with a shadow (B body, D shadow).
SEED_GRID :: Icon_Grid{
	"............",
	"....B.......",
	"...BD.......",
	"............",
	".......B....",
	"......BD....",
	"..B.........",
	".BD.........",
	"............",
	".....B......",
	"....BD......",
	"............",
}

// A five-petal bloom on a green stem (A/L petals, B center, D stem).
FLOWER_GRID :: Icon_Grid{
	"............",
	"....AAAA....",
	"...ALBBLA...",
	"...ABBBBA...",
	"...ALBBLA...",
	"....AAAA....",
	".....D......",
	".....D......",
	"....DD......",
	".....D......",
	".....D......",
	"............",
}

// Diagonal shaft, crystal tip — the tip's accent is the wand's tier.
WAND_GRID :: Icon_Grid{
	".........LA.",
	"........LAA.",
	".......hAL..",
	"......hh....",
	".....hh.....",
	"....hh......",
	"...hh.......",
	"..hh........",
	".hh.........",
	".h..........",
	"............",
	"............",
}

WOOD_LOG_GRID :: Icon_Grid{
	"............",
	"..DDDDDDDD..",
	".DBBBBBBBBD.",
	".DBAAABBBBD.",
	".DBABABBABD.",
	".DBAAABBBBD.",
	".DBBBBBABBD.",
	".DBBBBBBBBD.",
	"..DDDDDDDD..",
	"............",
	"............",
	"............",
}

LEAF_GRID :: Icon_Grid{
	".........h..",
	"........h...",
	"....DDDh....",
	"..DBBBLB....",
	".DBBBLBBD...",
	".DBBLBBBBD..",
	".DBLBBBBBD..",
	".DLBBBBBD...",
	".LBBBBBD....",
	".BBBBDD.....",
	".BDDD.......",
	"............",
}

STONE_BLOCK_GRID :: Icon_Grid{
	"............",
	"..tttttttt..",
	".tSSSSSSSSs.",
	".tSSsSSSSSs.",
	".tSSSSSStSs.",
	".tSSSSSSSSs.",
	".tSsSSSSSSs.",
	".tSSSSStSSs.",
	".tSSSSSSSSs.",
	".ssssssssss.",
	"............",
	"............",
}

// Grass cap (B/D) over a dirt block (A/a).
GRASS_TURF_GRID :: Icon_Grid{
	"............",
	"..BBBBBBBB..",
	".BBDBBBBBBD.",
	".DBBBBDBBBD.",
	".aAAAAAAAAa.",
	".aAaAAAAaAa.",
	".aAAAAAAAAa.",
	".aAAaAAAAAa.",
	".aAAAAAaAAa.",
	".aAAAAAAAAa.",
	".aaaaaaaaaa.",
	"............",
}

// A loose clod of earth (B) with dark clumps (D) and lit crumbs (L).
DIRT_GRID :: Icon_Grid{
	"............",
	"............",
	"..BBBBBBBB..",
	".BBLBBBDBBB.",
	".BBBBBBBBBB.",
	".BDBBLBBBBB.",
	".BBBBBBBDBB.",
	".BBLBBBBBBB.",
	".BBBBBDBBLB.",
	".DBBBBBBBBD.",
	".DDDDDDDDDD.",
	"............",
}

// A plank door (B leaf, D frame/seams, L rail highlight) with an iron knob (A).
DOOR_GRID :: Icon_Grid{
	"...DDDDDD...",
	"..DLLLLLLD..",
	"..DBBDBBBD..",
	"..DBBDBBBD..",
	"..DBBDBBBD..",
	"..DBBDBBBD..",
	"..DBBDBABD..",
	"..DBBDBBBD..",
	"..DBBDBBBD..",
	"..DBBDBBBD..",
	"..DBBDBBBD..",
	"...DDDDDD...",
}

// Bulging oak staves (B/L) bound by three dark hoops (D).
BARREL_GRID :: Icon_Grid{
	"............",
	"..DBLBLBD...",
	".DBLBLBLBD..",
	".DDDDDDDDD..",
	".BLBLBLBLB..",
	".BLBLBLBLB..",
	".DDDDDDDDD..",
	".BLBLBLBLB..",
	".BLBLBLBLB..",
	".DDDDDDDDD..",
	"..DBLBLBD...",
	"............",
}

// Two boards, grain (D) and nails (A).
PLANK_GRID :: Icon_Grid{
	"............",
	"............",
	".BBBBBBBBBB.",
	".BDBBBBBBAB.",
	".BBBBBDBBBB.",
	".DDDDDDDDDD.",
	".BBBBBBBBBB.",
	".BABBDBBBBB.",
	".BBBBBBBBDB.",
	"............",
	"............",
	"............",
}

// Rock chunk (B/D) with metal veins (A/a) and a sparkle.
ORE_GRID :: Icon_Grid{
	"............",
	"....DDDD....",
	"..DDBBBBDD..",
	".DBBaBBBBAD.",
	".DBAABBaBBD.",
	".DBBBWABBBD.",
	".DBaBBAABBD.",
	".DBBABBBaBD.",
	"..DBBaBBDD..",
	"...DDDDDD...",
	"............",
	"............",
}

CLOUD_STONE_GRID :: Icon_Grid{
	"............",
	"............",
	"....LLL.....",
	"..LLBBBLL...",
	".LBBBBBBBL..",
	".LBBBBBBBBL.",
	"..DBBBBBBD..",
	"...DDDDDD...",
	"............",
	"............",
	"............",
	"............",
}

CRYSTAL_GRID :: Icon_Grid{
	"......W.....",
	".....LA.....",
	".....LA.....",
	"....LLAA....",
	"....LLAA....",
	"...ALLAA....",
	"...ALLAAa...",
	"..W.LLAA.a..",
	"....LLAA.a..",
	".....AA.....",
	"............",
	"............",
}

BUCKET_GRID :: Icon_Grid{
	"............",
	".D........D.",
	"..D......D..",
	"..DDDDDDDD..",
	".DLLLLLLLLD.",
	".DBBBBBBBBD.",
	".DBBBBBBBBD.",
	"..DBBBBBBD..",
	"..DBBBBBBD..",
	"...DDDDDD...",
	"............",
	"............",
}

// The bucket brimming: the rim course and surface row read as fluid (accent,
// with an accent2 glint), plus a slosh bump peeking over the rim.
BUCKET_FULL_GRID :: Icon_Grid{
	"............",
	".D........D.",
	"..D..Aa..D..",
	"..DAAAAAAD..",
	".DAAaAAAAAD.",
	".DBBBBBBBBD.",
	".DBBBBBBBBD.",
	"..DBBBBBBD..",
	"..DBBBBBBD..",
	"...DDDDDD...",
	"............",
	"............",
}

// Garm's key — bow, shaft and bit.
KEY_GRID :: Icon_Grid{
	"....BBBB....",
	"...BB..BB...",
	"...BB..BB...",
	"....BBBB....",
	".....BD.....",
	".....BD.....",
	".....BD.....",
	".....BD.BB..",
	".....BD.BB..",
	".....BBBBB..",
	"............",
	"............",
}

// Cord (h), gold setting (g), gem (A) with a shine (L).
CHARM_GRID :: Icon_Grid{
	"...h.....h..",
	"..h.......h.",
	"..h.......h.",
	"..h.......h.",
	"...h.....h..",
	"....h...h...",
	".....ggg....",
	"....gAAg....",
	"....gALAg...",
	"....gAAg....",
	".....gg.....",
	"............",
}

HELM_GRID :: Icon_Grid{
	"............",
	"............",
	"...DBBBBD...",
	"..DBLLLLBD..",
	"..BBLLLLBB..",
	"..BBBBBBBB..",
	"..BBBBBBBB..",
	"..BD.BB.DB..",
	"..BD.BB.DB..",
	"..DD.BB.DD..",
	"............",
	"............",
}

CHESTPLATE_GRID :: Icon_Grid{
	"............",
	".DBBD..DBBD.",
	".BBBBDDBBBB.",
	".BLBBBBBBLB.",
	".BBBBBBBBBB.",
	"..BBLBBLBB..",
	"..BBBBBBBB..",
	"..BBBBBBBB..",
	"...BBBBBB...",
	"...DBBBBD...",
	"............",
	"............",
}

GAUNTLETS_GRID :: Icon_Grid{
	"............",
	"..BBB..BBB..",
	"..BBBD.BBBD.",
	"..BBBD.BBBD.",
	"..LBBD.LBBD.",
	"..LBBD.LBBD.",
	"..DBBD.DBBD.",
	"..BBBB.BBBB.",
	"..DDDD.DDDD.",
	"............",
	"............",
	"............",
}

GREAVES_GRID :: Icon_Grid{
	"............",
	"..DBBD.DBBD.",
	"..BLBB.BLBB.",
	"..BLBB.BLBB.",
	"..BLBB.BLBB.",
	"..BLBB.BLBB.",
	"..BBBB.BBBB.",
	"..DBBD.DBBD.",
	"..DBBD.DBBD.",
	"............",
	"............",
	"............",
}

BOOTS_GRID :: Icon_Grid{
	"............",
	"............",
	"...BBB.BBB..",
	"...BBB.BBB..",
	"...BBB.BBB..",
	"...LBB.BBL..",
	"..DBBB.BBBD.",
	".DBBBB.BBBBD",
	".DDDDD.DDDDD",
	"............",
	"............",
	"............",
}

// Workbench: mallet resting on a plank top, two legs.
BENCH_GRID :: Icon_Grid{
	"...ss.......",
	"..ssss......",
	"....hh......",
	".HHHHHHHHHH.",
	".hHHHHHHHHh.",
	"...hh..hh...",
	"...hh..hh...",
	"...hh..hh...",
	"...BB..BB...",
	"............",
	"............",
	"............",
}

// Sapling (B/D) in a pot (A/a).
TREE_GROWER_GRID :: Icon_Grid{
	"............",
	"....BBB.....",
	"...BDBBB....",
	"....BBB.....",
	".....h......",
	".....h......",
	"...aAAAa....",
	"...aAAAa....",
	"....aaa.....",
	"............",
	"............",
	"............",
}

// Faceted crystal (L/A/a) on a gold-collared stone plinth — the gem farm.
GEM_REPLICATOR_GRID :: Icon_Grid{
	"......W.....",
	".....LA.....",
	"....LLAA....",
	"...ALLAAa...",
	"....LLAA....",
	".....AA.....",
	"....gggg....",
	"...sSSSSs...",
	"...SSSSSS...",
	"..sSSSSSSs..",
	"..SSSSSSSS..",
	"............",
}

// Furnace body (B/D) with a fire window (A/a) and a gold cap.
SMELTER_GRID :: Icon_Grid{
	".....gg.....",
	"..DDDDDDDD..",
	"..DBBBBBBD..",
	"..DBBBBBBD..",
	"..DBAAAABD..",
	"..DBAaaABD..",
	"..DBAAAABD..",
	"..DBBBBBBD..",
	"..DBBBBBBD..",
	"..DDDDDDDD..",
	"............",
	"............",
}

// Blue crystal floating over a stone pedestal.
SKY_ALTAR_GRID :: Icon_Grid{
	".....AA.....",
	"....ALLA....",
	"...ALLLLA...",
	"....ALLA....",
	".....AA.....",
	"....SSSS....",
	"....SSSS....",
	"...SSSSSS...",
	"..SSSSSSSS..",
	"..ssssssss..",
	"............",
	"............",
}

// Rolled parchment tube lying flat — wide, not tall, unlike a square box (B
// body, L upper highlight, D outline/rolled-end caps).  A dark binding cord
// crosses the middle with a wax-seal rune (A) stamped beside it.
RUNE_SCROLL_GRID :: Icon_Grid{
	"............",
	"............",
	"............",
	".DDDDDDDDDD.",
	"DLLLLLLLLLLD",
	"DBBBDAABBBBD",
	"DBBBDAABBBBD",
	"DBBBDBBBBBBD",
	".DDDDDDDDDD.",
	"............",
	"............",
	"............",
}

// Anvil (B/D/L dark iron) with an ember glint (A) on the face.
FORGE_GRID :: Icon_Grid{
	"............",
	"............",
	"..LLLLLLLLL.",
	"..BBBABBBBL.",
	"...DBBBBD...",
	"....DBBD....",
	"....DBBD....",
	"...DBBBBD...",
	"..DBBBBBBD..",
	"..DDDDDDDD..",
	"............",
	"............",
}

// Stone altar carved with glowing runes (A).
RUNE_ALTAR_GRID :: Icon_Grid{
	"............",
	".tttttttttt.",
	".SSSSSSSSSS.",
	"...SSSSSS...",
	"...SASSAS...",
	"...SSAASS...",
	"...SASSAS...",
	"...SSSSSS...",
	"..SSSSSSSS..",
	".ssssssssss.",
	"............",
	"............",
}

// Cast ingot: trapezoid slab, lit top edge — tier palettes color the metal.
BAR_GRID :: Icon_Grid{
	"............",
	"............",
	"............",
	"...LLLLLL...",
	"..LBBBBBBD..",
	".LBBBBBBBBD.",
	".BBBBBBBBBD.",
	".DDDDDDDDDD.",
	"............",
	"............",
	"............",
	"............",
}

@(rodata)
item_icons := [Item]Item_Icon{
	.None = {},
	.Sword = {SWORD_GRID, PAL_IRON},
	.Pickaxe = {PICKAXE_GRID, {{150, 150, 165, 255}, {63, 91, 136, 255}, {198, 198, 212, 255}, {}, {}}},
	.Potion_Health = {POTION_GRID, {{220, 40, 40, 255}, {150, 22, 22, 255}, {255, 130, 130, 255}, {}, {}}},
	.Potion_Mana = {POTION_GRID, {{55, 55, 225, 255}, {30, 30, 150, 255}, {140, 140, 255, 255}, {}, {}}},
	.Mine_Wand = {WAND_GRID, {{}, {}, {210, 140, 240, 255}, {160, 60, 200, 255}, {}}},
	.Mine_Wand_Silver = {WAND_GRID, {{}, {}, {242, 242, 252, 255}, {205, 205, 225, 255}, {}}},
	.Mine_Wand_Gold = {WAND_GRID, {{}, {}, {255, 232, 130, 255}, {235, 195, 60, 255}, {}}},
	.Wood_Log = {WOOD_LOG_GRID, {{165, 120, 70, 255}, {95, 62, 36, 255}, {}, {125, 88, 48, 255}, {}}},
	.Leaf = {LEAF_GRID, {{58, 158, 48, 255}, {34, 108, 28, 255}, {112, 208, 88, 255}, {}, {}}},
	.Stone_Block = {STONE_BLOCK_GRID, {}},
	.Grass_Turf = {GRASS_TURF_GRID, {{56, 168, 56, 255}, {36, 126, 36, 255}, {}, {122, 86, 54, 255}, {92, 62, 38, 255}}},
	.Plank = {PLANK_GRID, {{180, 140, 90, 255}, {110, 80, 48, 255}, {}, {125, 125, 132, 255}, {}}},
	.Iron_Ore = {ORE_GRID, {{130, 130, 136, 255}, {94, 94, 102, 255}, {}, {190, 128, 95, 255}, {148, 94, 68, 255}}},
	.Silver_Ore = {ORE_GRID, {{130, 130, 136, 255}, {94, 94, 102, 255}, {}, {224, 224, 242, 255}, {168, 168, 195, 255}}},
	.Gold_Ore = {ORE_GRID, {{130, 130, 136, 255}, {94, 94, 102, 255}, {}, {240, 200, 55, 255}, {188, 148, 32, 255}}},
	.Gold_Rare_Ore = {ORE_GRID, {{146, 138, 118, 255}, {108, 100, 82, 255}, {}, {255, 222, 70, 255}, {212, 168, 40, 255}}},
	.Crafting_Bench = {BENCH_GRID, {{0, 0, 0, 255}, {}, {}, {}, {}}},
	.Tree_Grower = {TREE_GROWER_GRID, {{70, 170, 60, 255}, {40, 120, 35, 255}, {}, {150, 100, 55, 255}, {105, 70, 40, 255}}},
	.Smelter = {SMELTER_GRID, {{105, 95, 95, 255}, {68, 60, 60, 255}, {}, {230, 120, 35, 255}, {255, 200, 60, 255}}},
	.Iron_Bucket = {BUCKET_GRID, PAL_IRON},
	.Hell_Key = {KEY_GRID, {{220, 30, 60, 255}, {150, 16, 38, 255}, {}, {}, {}}},
	// Same rolled-scroll shape for all three; the seal wax (accent) carries the
	// tier's material — bronze (Plank), silver (Silver Bar), gold (Gold Bar) —
	// so A/B/C stop being pixel-identical (ground colors in item_table match).
	.Rune_Scroll_A = {RUNE_SCROLL_GRID, {{226, 206, 162, 255}, {34, 26, 22, 255}, {245, 232, 205, 255}, {182, 108, 58, 255}, {}}},
	.Rune_Scroll_B = {RUNE_SCROLL_GRID, {{214, 208, 214, 255}, {34, 26, 22, 255}, {236, 233, 240, 255}, {205, 205, 225, 255}, {}}},
	.Rune_Scroll_C = {RUNE_SCROLL_GRID, {{235, 218, 168, 255}, {34, 26, 22, 255}, {250, 240, 205, 255}, {235, 195, 60, 255}, {}}},
	.Sky_Rune_Scroll = {RUNE_SCROLL_GRID, {{150, 195, 235, 255}, {34, 26, 22, 255}, {200, 225, 250, 255}, {240, 250, 255, 255}, {}}},
	.Sky_Altar = {SKY_ALTAR_GRID, {{}, {}, {190, 230, 255, 255}, {90, 180, 255, 255}, {}}},
	.Cloud_Stone = {CLOUD_STONE_GRID, {{225, 235, 250, 255}, {172, 186, 215, 255}, {250, 252, 255, 255}, {}, {}}},
	.Aether_Crystal = {CRYSTAL_GRID, {{}, {}, {198, 255, 220, 255}, {110, 225, 160, 255}, {66, 168, 108, 255}}},
	.Runic_Sky_Ore = {ORE_GRID, {{168, 168, 190, 255}, {126, 126, 150, 255}, {}, {255, 140, 255, 255}, {198, 88, 220, 255}}},
	.Aether_Charm = {CHARM_GRID, {{}, {}, {210, 255, 230, 255}, {110, 230, 170, 255}, {}}},
	.Silver_Sword = {SWORD_GRID, PAL_SILVER},
	.Gold_Sword = {SWORD_GRID, PAL_GOLD},
	.Iron_Helm = {HELM_GRID, PAL_IRON},
	.Silver_Helm = {HELM_GRID, PAL_SILVER},
	.Gold_Helm = {HELM_GRID, PAL_GOLD},
	.Iron_Chestplate = {CHESTPLATE_GRID, PAL_IRON},
	.Silver_Chestplate = {CHESTPLATE_GRID, PAL_SILVER},
	.Gold_Chestplate = {CHESTPLATE_GRID, PAL_GOLD},
	.Iron_Gauntlets = {GAUNTLETS_GRID, PAL_IRON},
	.Silver_Gauntlets = {GAUNTLETS_GRID, PAL_SILVER},
	.Gold_Gauntlets = {GAUNTLETS_GRID, PAL_GOLD},
	.Iron_Greaves = {GREAVES_GRID, PAL_IRON},
	.Silver_Greaves = {GREAVES_GRID, PAL_SILVER},
	.Gold_Greaves = {GREAVES_GRID, PAL_GOLD},
	.Iron_Boots = {BOOTS_GRID, PAL_IRON},
	.Silver_Boots = {BOOTS_GRID, PAL_SILVER},
	.Gold_Boots = {BOOTS_GRID, PAL_GOLD},
	.Dvergr_Forge = {FORGE_GRID, {{105, 105, 125, 255}, {66, 66, 84, 255}, {150, 150, 172, 255}, {255, 140, 40, 255}, {}}},
	.Rune_Altar = {RUNE_ALTAR_GRID, {{}, {}, {}, {170, 110, 235, 255}, {}}},
	.Mine_Wand_Runic = {WAND_GRID, {{}, {}, {255, 190, 255, 255}, {230, 110, 250, 255}, {}}},
	.Runic_Sword = {SWORD_GRID, PAL_RUNIC},
	.Runic_Helm = {HELM_GRID, PAL_RUNIC},
	.Runic_Chestplate = {CHESTPLATE_GRID, PAL_RUNIC},
	.Runic_Gauntlets = {GAUNTLETS_GRID, PAL_RUNIC},
	.Runic_Greaves = {GREAVES_GRID, PAL_RUNIC},
	.Runic_Boots = {BOOTS_GRID, PAL_RUNIC},
	.Iron_Bar = {BAR_GRID, PAL_IRON},
	.Silver_Bar = {BAR_GRID, PAL_SILVER},
	.Gold_Bar = {BAR_GRID, PAL_GOLD},
	.Dimension_Spawner = {CRYSTAL_GRID, {{}, {}, {200, 255, 245, 255}, {70, 225, 195, 255}, {40, 160, 140, 255}}},
	.Dimension_Spawner_Gold = {CRYSTAL_GRID, {{}, {}, {255, 232, 130, 255}, {235, 195, 60, 255}, {178, 138, 28, 255}}},
	// Gem ladder — one crystal per depth layer, the palette carries the tier.
	.Emerald = {CRYSTAL_GRID, {{}, {}, {185, 255, 210, 255}, {60, 220, 130, 255}, {28, 150, 82, 255}}},
	.Jade = {CRYSTAL_GRID, {{}, {}, {225, 248, 230, 255}, {150, 210, 165, 255}, {92, 152, 108, 255}}},
	.Diamond = {CRYSTAL_GRID, {{}, {}, {240, 252, 255, 255}, {175, 225, 250, 255}, {105, 160, 205, 255}}},
	.Hel_Gem = {CRYSTAL_GRID, {{}, {}, {255, 145, 150, 255}, {220, 50, 80, 255}, {135, 18, 48, 255}}},
	// Machine box in dimensional teal — the snake miner's base.
	.Auto_Miner = {SMELTER_GRID, {{90, 96, 108, 255}, {56, 60, 70, 255}, {}, {80, 255, 220, 255}, {170, 255, 240, 255}}},
	.Dimension_Spawner_Runic = {CRYSTAL_GRID, {{}, {}, {235, 185, 255, 255}, {200, 120, 255, 255}, {130, 66, 178, 255}}},
	// Machine box in iron gray — the bulk store that counts past 99.
	.Silo = {SMELTER_GRID, {{120, 128, 142, 255}, {70, 76, 88, 255}, {}, {200, 210, 225, 255}, {240, 246, 255, 255}}},
	// Clod of loose earth dug from the shaft-mouth stratum.
	.Dirt = {DIRT_GRID, {{110, 78, 46, 255}, {78, 52, 30, 255}, {146, 108, 70, 255}, {}, {}}},
	// Wooden door — leaf, frame, rail highlight, iron knob.
	.Door = {DOOR_GRID, {{150, 100, 55, 255}, {92, 60, 32, 255}, {182, 130, 78, 255}, {60, 60, 68, 255}, {}}},
	// Foraged flower — petals, center, stem.
	.Flower = {FLOWER_GRID, {{210, 120, 30, 255}, {46, 140, 46, 255}, {255, 245, 175, 255}, {255, 220, 50, 255}, {}}},
	// Flower seeds — tan bodies with shadows.
	.Flower_Seed = {SEED_GRID, {{176, 146, 84, 255}, {110, 84, 44, 255}, {}, {}, {}}},
	// Flower bed — reuse the bloom icon (a planted crop).
	.Flower_Bed = {FLOWER_GRID, {{210, 120, 30, 255}, {46, 140, 46, 255}, {255, 245, 175, 255}, {255, 220, 50, 255}, {}}},
	// Oak barrel — staves, highlight, hoops.
	.Barrel = {BARREL_GRID, {{150, 100, 55, 255}, {92, 60, 32, 255}, {188, 138, 84, 255}, {}, {}}},
	// Void charm — amethyst shell around an emerald-lit abyss.
	.Void_Charm = {CHARM_GRID, {{}, {}, {188, 120, 235, 255}, {72, 18, 105, 255}, {45, 220, 135, 255}}},
	.Clay = {DIRT_GRID, {{166, 105, 72, 255}, {112, 66, 46, 255}, {205, 145, 105, 255}, {}, {}}},
	.Command_Wand = {WAND_GRID, {{}, {}, {220, 160, 112, 255}, {166, 105, 72, 255}, {}}},
	.Command_Wand_Emerald = {WAND_GRID, {{}, {}, {190, 255, 215, 255}, {60, 220, 130, 255}, {}}},
	.Command_Wand_Hel = {WAND_GRID, {{}, {}, {255, 155, 160, 255}, {220, 50, 80, 255}, {}}},
	.Clay_Golem = {SMELTER_GRID, {{166, 105, 72, 255}, {92, 54, 38, 255}, {}, {80, 220, 145, 255}, {225, 170, 120, 255}}},
	// Jade Ring — silver band, jade-lit charm.
	.Jade_Ring = {CHARM_GRID, {{}, {}, {205, 205, 225, 255}, {150, 210, 165, 255}, {92, 152, 108, 255}}},
	// Pond shore sand — same clod shape as Dirt/Clay, pale sandy palette.
	.Sand = {DIRT_GRID, {{225, 205, 150, 255}, {180, 158, 105, 255}, {245, 232, 200, 255}, {}, {}}},
	// Rune Coffer — the barrel silhouette in the chest's darker oak and iron.
	.Rune_Coffer = {BARREL_GRID, {{126, 68, 36, 255}, {74, 39, 24, 255}, {174, 102, 54, 255}, {}, {}}},
	// Lore, not progression — a damp pond-shore parchment with a deep-water seal.
	.Scroll_Of_Waters = {RUNE_SCROLL_GRID, {{198, 212, 224, 255}, {30, 34, 40, 255}, {232, 242, 250, 255}, {48, 128, 200, 255}, {}}},
	// Boiler — the machine box in riveted iron, its window a water sight-glass.
	.Boiler = {SMELTER_GRID, {{96, 102, 116, 255}, {58, 62, 74, 255}, {}, {90, 160, 220, 255}, {200, 230, 250, 255}}},
	// Steam Engine — the machine box in iron with a brass flywheel window.
	.Steam_Engine = {SMELTER_GRID, {{104, 100, 92, 255}, {62, 58, 52, 255}, {}, {200, 160, 60, 255}, {240, 212, 120, 255}}},
	// Filled buckets — the iron bucket body with the fluid's own colors on top.
	.Water_Bucket = {BUCKET_FULL_GRID, {{150, 150, 165, 255}, {100, 100, 115, 255}, {198, 198, 212, 255}, {48, 128, 200, 255}, {150, 205, 245, 255}}},
	.Lava_Bucket = {BUCKET_FULL_GRID, {{150, 150, 165, 255}, {100, 100, 115, 255}, {198, 198, 212, 255}, {230, 105, 20, 255}, {255, 200, 60, 255}}},
	.Magic_Lava_Bucket = {BUCKET_FULL_GRID, {{150, 150, 165, 255}, {100, 100, 115, 255}, {198, 198, 212, 255}, {160, 0, 220, 255}, {230, 140, 255, 255}}},
	// Gem Replicator — a faceted crystal in prismatic violet over a stone plinth.
	.Gem_Replicator = {GEM_REPLICATOR_GRID, {{}, {}, {235, 210, 255, 255}, {190, 130, 250, 255}, {120, 70, 180, 255}}},
	.GreenBerrie = {Icon_Grid{
		"............",
		"............",
		"....AAAg....",
		"..ABBBBLg...",
		".ABBBBLBDg..",
		".DBBBLBBBA..",
		".DBBLBBBBA..",
		".DBLBBBBA...",
		".ALBBBBA....",
		"..ABBDA.....",
		"............",
		"............",
	}, {{58, 158, 48, 255}, {34, 108, 28, 255}, {112, 208, 88, 255}, {0, 62, 0, 255}, {}}},
	.Green_Cave_Mushroom = {Icon_Grid{
		"............",
		"...LLLLLL...",
		"..LBBBBBBL..",
		".LBBWBBBBBL.",
		".BBBBBBWBBB.",
		".DBBWBBBBBD.",
		".DDDDDDDDDD.",
		"....AAAA....",
		"....AAAA....",
		"....AAAA....",
		"...aAAAAa...",
		"............",
	}, {{57, 235, 40, 255}, {28, 130, 30, 255}, {160, 255, 120, 255}, {228, 214, 176, 255}, {172, 152, 116, 255}}},
	// Magic Kettle - the machine box reusing the smelter silhouette in violet.
	.Magic_Kettle = {SMELTER_GRID, {{130, 90, 160, 255}, {78, 52, 96, 255}, {}, {210, 140, 255, 255}, {245, 210, 255, 255}}},
	// Mana Wheel - the machine box reusing the smelter silhouette, lighter violet.
	.Mana_Wheel = {SMELTER_GRID, {{170, 130, 200, 255}, {100, 74, 122, 255}, {}, {225, 190, 255, 255}, {250, 235, 255, 255}}},
	// A horizontal pipe segment: iron casing, a glowing fluid core down the middle.
	.Mana_Pipe = {Icon_Grid{
		"............",
		"............",
		"..DDDDDDDD..",
		"..DBBBBBBD..",
		".DBBAAAABBD.",
		"DBBBAaaaBBBD",
		"DBBBAaaaBBBD",
		".DBBAAAABBD.",
		"..DBBBBBBD..",
		"..DDDDDDDD..",
		"............",
		"............",
	}, {{160, 130, 190, 255}, {90, 68, 108, 255}, {}, {210, 140, 255, 255}, {245, 210, 255, 255}}},
	.Mossy_Stone = {Icon_Grid{
		"............",
		"............",
		"..aAAAAAAa..",
		".AAAAAAAAAA.",
		".LBABBBABBL.",
		".LBBBBBBBBL.",
		".BBBBBBBBBB.",
		".BBBDBBBBBB.",
		".BBBBBBBDBB.",
		".DBBBBBBBBD.",
		"..DDDDDDDD..",
		"............",
	}, {{130, 130, 136, 255}, {94, 94, 102, 255}, {168, 168, 176, 255}, {96, 170, 84, 255}, {54, 118, 50, 255}}},
}
